### PR TITLE
[WIP] Refactor imagenet

### PR DESCRIPTION
**Pull request by bearpelican**
@yaroslavvb initial refactor

Created a logger and meter class. I wanted to keep as much of the metric calculation and logging out of the training script. This way it's a bit easier to understand the training tricks we are using.

Still a bit more to cleanup. Feel free to add any suggestions

### CODE REVIEW

**Comment by bearpelican** [comment]
@yaroslavvb I put all the server files into the directory 'training'. 
https://github.com/diux-dev/cluster/pull/69/commits/e9162693936b5574d487aed71a753850436e2872#diff-2e1c1e714faa017fce6b7925c724322eR453

We are uploading the whole directory now and retaining the structure - so it should work nicely with sync.py
It was a bit easier to organize this way, but I can revert this commit if it's a problem!

**Comment by yaroslavvb** [comment]
Looks good to me! Yes, sync.py syncs the whole directory

**Comment by yaroslavvb** [comment]
Does it work?

**Comment by bearpelican** [comment]
On single p3. I'll try 4 in Virginia right now

**Pull request merged**
